2957 regen spatial extents
aodn/utilities pull request #272
Opened 2023-07-31 07:25 UTC by utas-raymondng

2023-08-03 01:12 UTC, craigrose requested changes

2023-08-06 23:56 UTC, utas-raymondng commented on geonetwork/spatialextents/src/main/java/au/org/aodn/geonetwork/spatialextents/UpdateSpatialExtents.java
> +        String dbCol = "geom";
@craigrose updated

2023-08-10 01:03 UTC, craigrose requested changes

2023-08-10 23:08 UTC, craigrose approved these changes

2023-08-10 23:08 UTC, merged